name: fix-workflow

on:
  push:
    branches:
      - fix
      - main
permissions:
  contents: write
  pull-requests: write 

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: 'node'
          package-name: 'your-package-name'
          release-as: '5.1.1'
          
